### PR TITLE
Validate ping url

### PR DESCRIPTION
**Pull request by nandi95**
## 📃 Description

I was trying to set up the ping url but I included the protocol which seems to not work with thie ping package. I added a little validation and removal of the protocol to remove this issue for others...

I'm not sure where the documentation should be updated to add this new error here: https://docs.speedtest-tracker.dev/help/error-messages

### ✏️ Changed

- added ping url validation
- removed ping url protocol

### CODE REVIEW

**Review by alexjustesen — APPROVED** [review]

**Comment by nandi95** [comment]
@alexjustesen I just realised this will fail ip addresses, that could prove to be an issue for people pinging dns like `1.1.1.1` so perhaps don't release just yet. I'll send a patch

**Comment by alexjustesen** [comment]
I was actually going to create a separate function for myself tonight for IP addresses so if you get to it first that works too!

**Comment by nandi95** [comment]
I think [Str::isUrl](https://github.com/laravel/framework/blob/11.x/src/Illuminate/Support/Str.php#L545) could be usefult here, it's used by the laravel validator too and handles ip addresses. You can define a list of accepted protocols too that should be accepted (and later stripped). I'll let you do it as the latter needs some more thought.

**Comment by alexjustesen** [comment]
I think we can use `isUrl` for validating the URL string. Looks like to validate the url or an IP address a protocol is required `http` or `https` which then looks like it validates as a URL instead.

```php

// URL validation
Str::isUrl('speedtest-tracker.dev'); // false
Str::isUrl('https://speedtest-tracker.dev'); // true

// IP address validation
Str::isUrl('1.1.1.1'); // false
Str::isUrl('https://1.1.1.1'); // true
```

Might be better to use `filter_var()` and validate the IP address so a protocol isn't required, example:

```php
filter_var('1.1.1.1', FILTER_VALIDATE_IP, FILTER_FLAG_IPV4 || FILTER_FLAG_IPV6); // true
```

**Pull request merged**
