### PR TITLE
Added server_id, server_host and server_name as tags for influxdb

### PR DESCRIPTION
**Pull request by UnAfraid**

### CODE REVIEW

**Comment by alexjustesen** [comment]
@UnAfraid can you run me through why you'd want those as tags vs. in the fields payload?

**Comment by UnAfraid** [comment]
> @UnAfraid can you run me through why you'd want those as tags vs. in the fields payload?

@alexjustesen So we can use 'group by' in InfluxQL
image

**Comment by alexjustesen** [comment]
@UnAfraid thanks, I don't use influx atm so not familiar with those requirements.

**Comment by alexdelprete** [comment]
Grouping could be useful.

**Review by alexjustesen — APPROVED** [review]

**Pull request merged**
