### PR TITLE
Add HealthCheck.io Notifications via Webhooks

### PR DESCRIPTION
**Pull request by svenvg93**
## 📃 Description

To close https://github.com/alexjustesen/speedtest-tracker/issues/1556 

Add support for Healthcheck.io notifications.

### ➕ Added

- Add Healthcheck.io to the notification page
- Add /fail to the url for Threshold notifications
- Add helperText to the Threshold toggle to inform user it will be sent the /fail path
- Add heathcheck.io to the settings migration

## 📷 Screenshots

Settings page
Scherm­afbeelding 2024-06-23 om 21 46 20

Healthcheck.io Completed test: 
Scherm­afbeelding 2024-06-22 om 17 11 42

Healthcheck.io Threshold breach
Scherm­afbeelding 2024-06-22 om 17 12 20

### CODE REVIEW

**Comment by alexjustesen** [comment]
Thanks for all the work on notification channels! Just a heads up I'm pointing the PRs at `develop-0.21.0` so we can collect them all for the next release.

**Comment by svenvg93** [comment]
Cant a way to make sure the threshold will be sent as last, so lets go!

**Comment by svenvg93** [comment]
@alexjustesen not push you, do you have any idea when these notifications pr will be merged. So can start working on the other item for adding the speedtest url in the notification

**Comment by alexjustesen** [comment]
> @alexjustesen not push you, do you have any idea when these notifications pr will be merged. So can start working on the other item for adding the speedtest url in the notification

I'd say probably this time next week. I'm catching up on client work (got to pay the bills) and then can re-focus my time on Speedtest Tracker without half-assing it.

**Comment by svenvg93** [comment]
> > @alexjustesen not push you, do you have any idea when these notifications pr will be merged. So can start working on the other item for adding the speedtest url in the notification
> 
> I'd say probably this time next week. I'm catching up on client work (got to pay the bills) and then can re-focus my time on Speedtest Tracker without half-assing it.

No worries, bills need to get paid :)

**Pull request merged**
