### PR TITLE
[Chore] Remove support for sqlite

### PR DESCRIPTION
**Pull request by alexjustesen**
# Description

This PR removes SQLite as the default database option, steps to use SQLite can be referenced from the [Laravel ](https://laravel.com/docs/10.x/database#sqlite-configuration) docs should that still want to be used.

### Removed
- SQLite as the default database

### CODE REVIEW

**Comment by AleksCee** [comment]
Without a way to migrate with the braking changes?

**Comment by luckman212** [comment]
So if we don't have an InfluxDB set up, do we now need to stand one up? No more single-container instance?

**Comment by alexdelprete** [comment]
> So if we don't have an InfluxDB set up, do we now need to stand one up? No more single-container instance?

you need mysql/mariadb or postgresql as main db.

Influxdb is optional, to export data for better analysis/graphs, etc. it's not mandatory.

**Comment by alexjustesen** [comment]
> Without a way to migrate with the braking changes?

I'm not calling this a breaking change as it's still supposed by the framework it will just no longer be the recommended solution for this application so it's been removed as the default.

**Comment by alexjustesen** [comment]
Also to note, this impacts new installs not existing.

**Comment by AleksCee** [comment]
> Also to note, this impacts new installs not existing.

Ok this is a info I can't figure out from the Changnotes. 
Then it's no braking change. 👍🏻
Anyway it's can be a good idea to migrate the data, are you plan a support feature to do that?

Thx, Alex

**Comment by alexjustesen** [comment]
@AleksCee once I'm through these Docker issues import/export/backup is the next priority.

**Pull request merged**
