### PR TITLE
Add Support for Slack Notifications via Webhook

### PR DESCRIPTION
**Pull request by svenvg93**
## 📃 Description

This PR adds support for Slack notifications. As it was listed here https://github.com/alexjustesen/speedtest-tracker/issues/40 
It been tested with Slack Apps and Legacy Webhooks

### ➕ Added

- Slack Notifications

## 📷 Screenshots

Slack App
Scherm­afbeelding 2024-06-11 om 22 15 38

Legacy Webhooks
image

### CODE REVIEW

**Comment by alexjustesen** [comment]
I'm going to circle back around to this PR early next week, leaving myself https://laravel.com/docs/11.x/notifications#slack-notifications for consideration on whether we should "just" support Slack Apps.

**Comment by alexjustesen** [comment]
@svenvg93 when ya got a chance can you resolve conflicts?

**Comment by svenvg93** [comment]
> @svenvg93 when ya got a chance can you resolve conflicts?

Done, should be all good now. I hope 😅

**Review by alexjustesen — APPROVED** [review]

**Comment by DoctorT07** [comment]
he doent work for me

**Pull request merged**
