### PR TITLE
[WIP] Add day/week/month average to the Dashboard

### PR DESCRIPTION
**Pull request by svenvg93**
📃 Description

This PR adds the an average of the download, upload and ping over the last day, week, month

📷 Screenshots
Scherm­afbeelding 2024-08-05 om 22 55 14

It is still a work in progress, as I was also thinking about adding a full separate page for showing average numbers for all charts on the dashboard.
@alexjustesen  Please let me know what you think and what you would like to see, so I can adjust it to your wishes 😁

### CODE REVIEW

**Comment by alexjustesen** [comment]
Funny enough I was thinking about this the other day, I'm not sure I want to do it in a stat card and was instead thinking about adding it to the charts.

Filament [charts](https://filamentphp.com/docs/3.x/widgets/charts) are extensions of [ChartJS](https://www.chartjs.org/docs/latest/) so I was thinking the "better" idea from a visual standpoint would be to use the [line annotations](https://www.chartjs.org/chartjs-plugin-annotation/3.0.1/guide/types/line.html) to show the calculated average for that given timeframe.

**Comment by svenvg93** [comment]
That might be a better idea yeah, Will check it out! :)

**Comment by svenvg93** [comment]
More like this? 

image

**Comment by svenvg93** [comment]
If I turn off the data points it looks a much cleaner. Also changed the average to a dotted line.

Schermopname 2024-08-07 om 18 35 13

Just need to find a way if there is a only one data point in the selected time frame 

@alexjustesen Any thoughts on this

**Comment by alexjustesen** [comment]
Oh I'm liking this! Can you commit your chart code so I can take a look? I'm thinking we should only average the data if there are more than 1 records in the chart results.

**Comment by svenvg93** [comment]
> Oh I'm liking this! Can you commit your chart code so I can take a look? I'm thinking we should only average the data if there are more than 1 records in the chart results.

Now the Average line is only shown with 2 or more data points. 
Only thing that I haven't figured out yet is that one there is only one data point, for example the first one the chart is empty as the data points are not shown anymore. 

For now I only did for the download charts; happy to do the others as well, put in a different branch so you can fine tune it if needed.

**Comment by svenvg93** [comment]
While I was looking at the other open FR for the charts I came up with this idea. 

image

It will do: 

[x] - Show the Average over the selected time frame in a red dotted line
[x] - Fill the background of the Download/upload/etc with 10% 

356527381-377b9eb7-14d6-476c-b940-6cac1300e85e-2

[x] - Add a Start - end date picker for a better selection of the time range. Applies to all charts
[x] - Add a general time range selection  like 24 Hours, 1 Week, 1 Month, etc Applies to all charts
[x] - Add a Server selection, so when testing with multiple servers the graphs will show it for the selected servers at the same time.
[x]- Show only the data points (dots on the line)  in the charts if there are 5 or less data points. 

I understand its a big redesign of the current dashboard, but it will cover most of the items listed in the milestone https://github.com/alexjustesen/speedtest-tracker/milestone/5 

Please let me know your thoughts about it :)

**Comment by alexjustesen** [comment]
I need a few days to noodle this over but I'm going to drop a reference to the docs for a page filter section that I also had in mind which aligns to your example above.

https://filamentphp.com/docs/3.x/panels/dashboard#filtering-widget-data

**Comment by svenvg93** [comment]
In case you're interested , just for my own learnings I made branch with a date picker based on the changed in this pr. 
The default time range can be set in a env `CHART_TIME_RANGE` 

https://github.com/svenvg93/speedtest-tracker/tree/dashboard-remake 

Scherm­afbeelding 2024-08-12 om 22 31 13

**Comment by alexjustesen** [comment]
Oh hell yeah! I'll look at the forked branch later tonight but I think we're off in the right direction.

**Comment by svenvg93** [comment]
Cool! Curious to see what you think about it :) 

Only thing i'm not sure about is the 
`Add a Server selection, so when testing with multiple servers the graphs will show it for the selected servers at the same time.` As it might get messy in the graphs. 

Also looking to add a Failed test in the charts, just need to get some failed tests in the db to play around with the visual part haha

**Comment by alexjustesen** [comment]
So we don't make it too complex skip the multi-server comment for now along with annotations for failures. Will help me quickly test too.

**Comment by svenvg93** [comment]
Cool! I will merge it all in one branch and make a clean new pr for it :)

**Pull request closed without merging**
