### PR TITLE
Fix issue with Notify on every speedtest run failing 

### PR DESCRIPTION
**Pull request by tgregory86**
Notify on every speedtest run failing:

[2024-06-11 12:38:08] production.ERROR: Undefined variable $event {"exception":"[object] (ErrorException(code: 0): Undefined variable $event at /app/www/app/Mail/SpeedtestCompletedMail.php:51) [stacktrace]

## 📃 Description

A short description of the pull request changes should go here and the sections below should list in detail all changes. You can remove the sections you don't need.

Fix issue with Notify on every speedtest run failing 

### ➕ Added

- one
- two

### ✏️ Changed

- /app/www/app/Mail/SpeedtestCompletedMail.php 
- two

### 🔧 Fixed

- one
- two

### 🗑️ Removed

- one
- two

## 📷 Screenshots

If this PR has any UI/UX changes it's strongly suggested you add screenshots here.

### CODE REVIEW

**Comment by alexjustesen** [comment]
@tgregory86 looks like the same issue in the threshold file as well, do you mind committing a fix for that too?

**Review by alexjustesen — CHANGES_REQUESTED** [review]
Please also fix threshold reference as well.

**Comment by svenvg93** [comment]
@alexjustesen Sorry for causing this bug :( 
Just for my understanding why is mail using `this` and the others `event`

**Comment by alexjustesen** [comment]
> @alexjustesen Sorry for causing this bug :( Just for my understanding why is mail using `this` and the others `event`

It was a my-bad, I missed it in the review. Mail uses `$this->` because the `result` is passed directly into the mailable and the mailable doesn't take the full event just the data.

- Listener passing the `result`: https://github.com/alexjustesen/speedtest-tracker/blob/main/app/Listeners/Mail/SendSpeedtestCompletedNotification.php

**Comment by svenvg93** [comment]
> > @alexjustesen Sorry for causing this bug :( Just for my understanding why is mail using `this` and the others `event`
> 
> It was a my-bad, I missed it in the review. Mail uses `$this->` because the `result` is passed directly into the mailable and the mailable doesn't take the full event just the data.
> 
> * Listener passing the `result`: https://github.com/alexjustesen/speedtest-tracker/blob/main/app/Listeners/Mail/SendSpeedtestCompletedNotification.php

Thanks for explaining!

**Comment by tgregory86** [comment]
> Please also fix threshold reference as well.

Done

**Review by alexjustesen — APPROVED** [review]

**Pull request merged**
