### PR TITLE
[Feature] CLI to update general settings

### PR DESCRIPTION
**Pull request by alexjustesen**
# Description

This PR introduces a CLI command to update the general settings which will hopefully help solve the `500 error` on that page. Might help fix issues like in #943.

## Use

1. Open the terminal of the container.
2. Run `php artisan app:update-general-settings`.
3. Follow the prompts.

### Added

- cli to update general settings

### CODE REVIEW

**Comment by adam1991tomlinson** [comment]
good morning i have been following 500 server error and followed till this and now its saying GMT (london) is not a valid time zone
Screenshot 2023-12-18 093321

**Comment by alexjustesen** [comment]
> good morning i have been following 500 server error and followed till this and now its saying GMT (london) is not a valid time zone
> Screenshot 2023-12-18 093321
> 

`GMT` might not be valid in PHP's time zone list. Use `UTC` instead.

**Comment by adam1991tomlinson** [comment]
Just googled it and GMT is Europe/London and it's on the PHPS list

**Comment by alexjustesen** [comment]
> Just googled it and GMT is Europe/London and it's on the PHPS list

Interesting, use UTC for now and I'll check the validation tonight on that one.

**Comment by alexjustesen** [comment]
So looks like GMT is no longer a valid time zone that's provided from the embedded method. Def suggest using `Europe/London` or `UTC` instead.

https://www.php.net/manual/en/timezones.others.php

**Pull request merged**
