### PR TITLE
[Feature] Add markdown content type for gotify notification

### PR DESCRIPTION
**Pull request by chiragkrishna**
## 📃 Description

Enables markdown feature in Gotify Notification

## 📷 Screenshots
**Before**
Screenshot from 2024-09-17 20-48-04

**After**
Screenshot from 2024-09-17 20-40-05

### CODE REVIEW

**Comment by alexjustesen** [comment]
@chiragkrishna I have no doubts this is likely a supported standard but to make it easier to track can you link to Gotify supporting docs that specify markdown support? Happy to merge the formatting change after.

**Comment by chiragkrishna** [comment]
@alexjustesen yea sure here is the Gotify [Documentation](https://gotify.net/docs/msgextras#clientdisplay)

**Review by alexjustesen — APPROVED** [review]

**Comment by alexjustesen** [comment]
Note to self, once the latest shift branch is merged updated this branch to resolve the linting errors.

**Review by alexjustesen — APPROVED** [review]

**Comment by alexjustesen** [comment]
@chiragkrishna can you fix the lint errors, once updated happy to merge. Thanks!

**Comment by chandan-2212** [comment]
@alexjustesen , pls share your current errors.

**Review by alexjustesen — APPROVED** [review]

**Pull request merged**
