### PR TITLE
[Feature] Adding scheduled latency tests

### PR DESCRIPTION
**Pull request by svenvg93**
## 📃 Description

Another way to monitor your internet connection, in addition to using speed tests, is by measuring latency. This pull request introduces the ability to measure latency and display the results.

to close: https://github.com/alexjustesen/speedtest-tracker/issues/826

### ➕ Added

- Add a RecentLatencyChartWidget to show the results of the test
   - Left Axis show the average ms
   - Right Axis show the percentage of packet loss
- Add RunScheduledLatencyTests to execute the tests based on the schedule
- Add ExecuteLatencyTest to do the testing and send the results the database
- Add the database migration to store the results 
- Add a Settings Page
     - Enable the latency tests
     - Set the ping count
     - Set the cron job
     - Change the view from list (full) or grid (half)
     - Add Targets with an Display name and URL
- Add Latency page to show the charts for each Display name set in the settings. 
- Add a Description for the targets in the title header. 

### Todo

- Add the Date range selection, will be done after the merge of https://github.com/alexjustesen/speedtest-tracker/pull/1669 
- Add the new chart config options of https://github.com/alexjustesen/speedtest-tracker/pull/1669 
- Test the various scenarios for when there is no internet, no dns etc 
- Threshold
   - x % of Packet Loss
   - Latency increase by x 
- Notifications for thresholds

## 📷 Screenshots

Charts:
List view;
image

Grid View;
image

Settings:
image

### CODE REVIEW

**Comment by svenvg93** [comment]
@alexjustesen Before I work on the last to do points. Is this how you like to see the latency/uptime monitoring?

**Comment by Kristoffeh** [comment]
> @alexjustesen Before I work on the last to do points. Is this how you like to see the latency/uptime monitoring? Another idea I had was to do pre-defined targets to major CDNs like Cloudflare, AWS, Google, Fastly etc

This is impressive, all of these are great changes. Its probably a good idea to have pre-defined targets, but allowing users to remove/customize them themself.

**Comment by svenvg93** [comment]
> This is impressive, all of these are great changes. Its probably a good idea to have pre-defined targets, but allowing users to remove/customize them themself.

That might be an option as well yess.

**Comment by svenvg93** [comment]
Closing, will be picked up agian in a later stage.

**Pull request closed without merging**
