### PR TITLE
Add Gotify Notifications via Webhook

### PR DESCRIPTION
**Pull request by svenvg93**
## 📃 Description

As listed in https://github.com/alexjustesen/speedtest-tracker/issues/40 this PR will add support for Gotify

### ➕ Added

- Gotify to the Notification page
- Add Gotify to the settings migration
- Add notification view

## 📷 Screenshots

Scherm­afbeelding 2024-06-22 om 10 04 19

image

### CODE REVIEW

**Comment by svenvg93** [comment]
@alexjustesen No clue why the lint checks are failing.  I haven't even touch these files 😅  and the local test it a pass. 
Scherm­afbeelding 2024-06-25 om 00 21 04

**Comment by alexjustesen** [comment]
Duster got updated in the pipeline but I forgot to bump the package, #1569 fixes that. You can update your branches from `develop-0.21.0` to get the latest deps and then run `sail composer install`.

**Review by alexjustesen — APPROVED** [review]

**Comment by Retract1822** [comment]
Thank you! I've been waiting for this. When can we expect this to be added into the package release/docker image?

**Comment by alexjustesen** [comment]
> Thank you! I've been waiting for this. When can we expect this to be added into the package release/docker image?

Hopefully later this week, @svenvg93 has done a fantastic job adding more notification channels and the bottleneck is my "free" time has been pretty tight lately for open-source projects.

**Comment by svenvg93** [comment]
> > Thank you! I've been waiting for this. When can we expect this to be added into the package release/docker image?
> 
> Hopefully later this week, @svenvg93 has done a fantastic job adding more notification channels and the bottleneck is my "free" time has been pretty tight lately for open-source projects.

Now I just hope it all works as tested ;)

**Comment by Retract1822** [comment]
> > Thank you! I've been waiting for this. When can we expect this to be added into the package release/docker image?
> 
> Hopefully later this week, @svenvg93 has done a fantastic job adding more notification channels and the bottleneck is my "free" time has been pretty tight lately for open-source projects.



> > > Thank you! I've been waiting for this. When can we expect this to be added into the package release/docker image?
> > 
> > 
> > Hopefully later this week, @svenvg93 has done a fantastic job adding more notification channels and the bottleneck is my "free" time has been pretty tight lately for open-source projects.
> 
> Now I just hope it all works as tested ;)

I realise how time this must take from your personal lives so wanted you to know that it's very much appreciated and thank you for the great product!

**Pull request merged**
