### PR TITLE
Report bits not bytes

### PR DESCRIPTION
**Pull request by alexjustesen**
### Added
- helpers for `formatBytesToBits` and `formatBits`

### Changed
- show results in descending order
- updated composer dependencies

### Fixed
- this PR fixes an issue first reported in #35 where the panel is reporting `MB/s` instead of `Mbps`

### Removed
- manually set php ini settings, not needed

## Preview
image
_Speedtest Results_

### CODE REVIEW

**Comment by alexdelprete** [comment]
Alex, could you push a beta release so we can upgrade without too many hassles?

**Comment by JourneyOver** [comment]
Yes please, can you push a beta release for this by chance? also even though it doesn't pertain to this issue, does TZ data just not work? the `Created at` time is still displaying in UTC, even though I have the TZ stuff setup, and even have
```
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
```

set up.

**Comment by alexjustesen** [comment]
Working on it, I need to get permissions sorted first for the sqlite db and config.yml file and then I'm planning on tagging a version

**Comment by alexdelprete** [comment]
Will you put in the SSL workaround?

**Pull request merged**
