### PR TITLE
[Bug] Refactor usage of time zones

### LINKED ISSUE #194: Scheduled Speedtests will always run one hour late
**Describe the bug**
Hi,
hope you are doing well and thank you for this project! I started to set this up yesterday on my Synology NAS to replace Speedtest Tracker (the original) however I'm currently seeing an issue with the Speedtest scheduling. If I set this up via cron expression, basically the same as with the original Speedtest Tracker I'm seeing that it will always run 1 hour late. E.g. if I set this to 3 PM it will run at 4 PM and I can't seem to figure out why, so I'm thinking this is a Bug. To reproduce and show it on a Screenshot I had picked a simple time. Maybe something to do with the set Timezone?

**To Reproduce**
1. Go to General Settings
2. Set cron expression to something like '0 15 * * *'
3. Wait for the schedule expected time
4. See that the Test will not run until one our late

**Expected behavior**
Scheduled Tests should be run at the exact time I define them via cron expression

**Screenshots**
Error

**Logs**
No logs showing the actual run of the test, Logiles have the correct timestamp. Executing into the container will show the time is correct:
```
root@1bddb13f78d3:/var/www/html# date -d "$(curl -sI google.com| grep -i '^date:'|cut -d' ' -f2-)"
Mon Dec  5 18:55:23 CET 2022
root@1bddb13f78d3:/var/www/html# uptime
 18:55:26 up 235 days, 11:52,  0 users,  load average: 0.24, 0.39, 0.29
root@1bddb13f78d3:/var/www/html
```

**Additional context**
How I'm running the container:
```
docker run --restart=always --name=speedtest-tracker -d \
    -v /volume1/docker/speedtest-tracker:/config \
    -e "TZ=Europe/Berlin" \
    -e "PUID=1026" \
    -e "PGID=100" \
    -p 5811:80 \
    ghcr.io/alexjustesen/speedtest-tracker:latest
```

### LINKED ISSUE #649: Scheduled test is not running at the correct, scheduled time
In general settings, I have `0 5 * * *` as my scheduled speed test, which should be every day at 5 AM. However, it is running the speed test every day at 22:00, which is 10 PM. I don't believe it's a timezone issue because when I manually run a test, the shown last run time is correct.

### LINKED ISSUE #659: Dashboards are always presented in GMT
**Describe the bug**
No matter what I set `TZ` to in the environment or `General -> Timezone` in the UI, the dashboard always displays graphs and the "last speed run" in GMT.

**To Reproduce**

Look at the dashboard.

**Expected behavior**
The dashboard to honor the timezone set.

**Environment (please complete the following information):**
 - OS: Linux
-  Architecture: amd64
 - Browser:  safari
 - Version: v0.11.17

**Screenshots**

Notice current local time in upper right corner, but time showing in the dashboard:
image

**Logs**
If applicable, check the logs for any error that might of occurred.

**Additional context**

### LINKED ISSUE #805: Timezone on WEB Not Correct
Running on Docker through Linux mint.  Selected America/Chicago (US Central TIme) via setup page.  Times showing on the Web page are roughly 5 hours ahead of the time.  I have verified that the time on the server is correct tz.

### LINKED ISSUE #859: Docker compose Install failed with "init: error mounting "/etc/localtime" to rootfs at "/etc/localtime"
**Describe the bug**
Created docker-compose.yml as per documentation.
"docker compose up"
Get this error message after "Initializing database files":
`Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/etc/localtime" to rootfs at "/etc/localtime": mount /etc/localtime:/etc/localtime (via /proc/self/fd/6), flags: 0x5001: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
`
Installing on Alpine-linux lxc container under ProxMox.

**To Reproduce**
Install as above.

**Expected behavior**

Install worked

**Environment (please complete the following information):**
 - OS: Alpine LXC
-  Architecture: amd64
 - Browser SSH to Container
 - Version: Latest

**Screenshots**
**Logs**
**Additional context**

### LINKED ISSUE #916: "Latest result" string shows wrong phrasing. Gets confused between past and future.
**Describe the bug**
The `Latest result` is showing me that the latest test was in the future. That's a bit odd :)

Maybe this has something to do to the Timezones bug and the logic behind the string is getting confused.

**Expected behavior**
The string should be "Latest result: 5 minutes ago" in the screenshot below. The Screenshot was taken at 21:05.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by alexjustesen**
⚠️ WIP - this PR isn't ready for primetime just yet.

# Description

This PR looks to address the issues around usage of time zones throughout the application. #846 was a useful exercise in an overly complex solution.

## Guiding requirements

- [x] Records should be stored in the database as UTC.
- [x] Scheduled should be aware of the time zone setting.
- [x] Cron evaluation should be aware of the time zone setting.
- [x] Since last result should be aware of the time zone setting.
- [x] Default display timezone is in UTC.
- [x] Results table should have the datetime based on the time zone setting.
- [x] Graphs should have the correct datetime based on the time zone settings.
- [x] InfluxDB should still receive the UTC based timestamp.
- [x] Passing the host OS's time zone is no longer needed.
- [x] Passing a `TZ=` environment variable is no longer needed.

## To-dos

- [x] More testing to make this as simple as possible.
- [ ] Update docs to correctly set the time zone.

## Reference issues

- closes #194
- #242
- #631 
- closes #649 
- closes #659
- #696 
- #800  
- closes #805 
- closes #859 
- closes #916 

### Changed

- set scheduled tasks time zone
- set `$cron->isDue` to use the current local time to evaluate if a cron is due

### Fixed

- the jank and complexity surrounding dealing with time zones

### Removed

- no longer need to mount `'/etc/localtime:/etc/localtime:ro'` to pass the host machine's time
- no longer need to pass `TZ` as an environment variable

## Screenshots

image
_Sanity checking time zones, datetimes and conversions to local time_

### CODE REVIEW

**Comment by alexjustesen** [comment]
Sometimes simpler is better, this solution seems to fix most of the issues with time zones but going to be testing it a bit more before merging and tagging a release.

**Comment by Deses** [comment]
Here's hoping this fixes timezone issues once and for all!

**Comment by alexjustesen** [comment]
> Here's hoping this fixes timezone issues once and for all!

As excited as the community might be you have no idea how excited I am...

**Comment by Deses** [comment]
> > Here's hoping this fixes timezone issues once and for all!
> 
> As excited as the community might be you have no idea how excited I am...

Oh I can imagine, I've dealt with timezones before and it's an absolute hell.

**Comment by alexjustesen** [comment]
Merging this PR into dev and will be tagging a `v0.14.0-beta1` version shortly. Docs will be updated when stable and the steps to update your container are in #935.

**Pull request merged**
