### PR TITLE
Laravel 10.x Shift

### PR DESCRIPTION
**Pull request by alexjustesen**
This pull request includes the changes for upgrading to Laravel 10.x. Feel free to commit any additional changes to the `shift-90275` branch.

**Before merging**, you need to:

- Checkout the `shift-90275` branch
- Review **all** pull request comments for additional changes
- Run `composer update` (if the scripts fail, add `--no-scripts`)
- Clear any config, route, or view cache
- Thoroughly test your application ([no tests?](https://laravelshift.com/laravel-test-generator), [no CI?](https://laravelshift.com/ci-generator))

If you need help with your upgrade, check out the [Human Shifts](https://laravelshift.com/human-shifts). You may also join the [Shifty Coders](https://laravelshift.com/shifty-coders) Slack workspace to level-up your Laravel skills.

## Changelog

In addition to the Shift changes the follow has been changed.

### Changed
- refactored rule `ValidateCronExpression` to `Cron`
- refactored Telegram test notification, this lays the groundwork and a pattern for the work planned for `v0.19.0` (notification refactor)

### CODE REVIEW

**Comment by alexjustesen** [comment]
:information_source: Laravel 10 deprecated the `ImplicitRule`, `InvokableRule`, and `Rule` contracts in favor of using the new, streamlined `ValidationRule` contract. These contracts will be removed in a future version of Laravel.

Given the change in the method names and return type, Shift can not reliably automate this change. At your convenience, you should review these custom validation rules and update them to implement the `ValidationRule` contract.

- [ ] app/Rules/ValidCronExpression.php

**Comment by alexjustesen** [comment]
:warning: Shift upgraded your configuration files by defaulting them and merging your _true customizations_. These include values which are not changeable through core `ENV` variables.

You should [review this commit](https://github.com/alexjustesen/speedtest-tracker/pull/576/commits/a2bf1a17318a8d1224499da677d1bea6eca52758?w=1) for additional customizations or opportunities to use new `ENV` variables. If you have a lot of customizations, you may undo this commit with `git revert a2bf1a17` and make the [config file changes](https://github.com/laravel-shift/laravel-9.x/pull/4/commits/5401110f1f41793ecdce268495768abfa4a53dfe) manually.

**Comment by alexjustesen** [comment]
:information_source: Shift [updated your dependencies](https://github.com/alexjustesen/speedtest-tracker/pull/576/commits/225e72b272965eca3ca2cb59783444ffa50b2237?w=1) for Laravel 10. While many of the popular packages are reviewed, you may have to update additional packages in order for your application to be compatible with Laravel 10. Watch [dealing with dependencies](https://laravelshift.com/videos/update-incompatible-composer-dependencies) for tips on handling any Composer issues.

The following dependencies were updated by a major version and may have their own changes. You may check their changelog for any additional upgrade steps.

- [ ] [laravel-notification-channels/telegram](https://packagist.org/packages/laravel-notification-channels/telegram)

**Comment by alexjustesen** [comment]
:warning: Shift detected you are running Laravel Sail. If you have not customized your stack, you should run `php artisan sail:install` to regenerate the latest `docker-compose.yml`. Otherwise, Shift attempted to update Sail for PHP 8.1. However, you should review your `docker-compose.yml` to ensure your stack is running PHP 8.1 or higher.

**Comment by alexjustesen** [comment]
:information_source: Laravel 9 adopted [anonymous migrations](https://laravel-news.com/laravel-anonymous-migrations). Shift [automated this change](https://github.com/alexjustesen/speedtest-tracker/pull/576/commits/ac5ef6aa4d5845dfc685acb49e2b35de78d2c464?w=1) to align with modern Laravel conventions and avoid naming migrations.

**Comment by alexjustesen** [comment]
:information_source: Laravel renamed the `password_resets` table to `password_reset_tokens`. While an optional change, Shift detected you have a migration for this table and [created a migration](https://github.com/alexjustesen/speedtest-tracker/pull/576/commits/7b9a3b01362ec171f334a58d1f7e6b199d105353?w=1) to rename it as well as updated the reference in your `config/auth.php` file. Be sure to run `php artisan migrate` to complete your upgrade.

**Comment by alexjustesen** [comment]
:warning: Laravel 10 has added a return type of `array` to the Event `broadcastOn` and Notification `via` methods. However, you may still return a single channel from these methods.

Shift added the `array` return type to these methods in the following classes. You should review them to ensure you are returning an `array`, or remove the return type.

- [ ] app/Telegram/TelegramNotification.php

**Comment by alexjustesen** [comment]
:information_source: Laravel 10 added PHP type hints to all user-land code included in a new Laravel application. In an effort to modernize your code, Shift [added type hints](https://github.com/alexjustesen/speedtest-tracker/pull/576/commits/effc3bdf7bf1e33baf709617aa12d5cd9b2fb241?w=1) to any method which is used by Laravel.

**Comment by alexjustesen** [comment]
:information_source: Now with type hints in your code, defining types within PHP DocBlocks is redundant. Laravel has removed all of the `@param` and `@return` tags from its DocBlocks where types are defined with PHP. Similarly, Shift [removed these tags](https://github.com/alexjustesen/speedtest-tracker/pull/576/commits/2375f90b73281db377a1e49c8a896147b65a412a?w=1) from any DocBlock where the code now has _equivalent_ type hints.

**Comment by alexjustesen** [comment]
:information_source: Shift understands developers have different preferences when it comes to type hints. All of Shift's automation is done in nice, atomic commits. This makes it easier to undo any of the changes Shift makes.

If you wish to undo the changes relating to type hints, you may run:

- `git revert 2375f90` to revert the DocBlock changes.
- `git revert 470ac78` to revert the type hints added from DocBlocks.
- `git revert effc3bd` to revert the type hints added for Laravel 10.

**Comment by alexjustesen** [comment]
:information_source: All of the underlying Symfony components used by Laravel have been upgraded to Symfony 6.2. Shift detected references to Symfony classes within your application. You should review the [Symfony change log](https://github.com/symfony/symfony/blob/6.2/UPGRADE-6.2.md) for any additional changes.

**Comment by alexjustesen** [comment]
:warning: Laravel 10 requires Composer 2.2 or higher. You should verify the Composer version in your environments by running `composer --version` to ensure it meets this new requirement. If necessary, run `composer self-update` to update Composer.

**Comment by alexjustesen** [comment]
:tada: Congratulations, you're now running the latest version of Laravel!

Next, you may optionally run the following _Shifts_ to ensure your application is fully upgraded, adopts the latest Laravel conventions, and easier to maintain in the future:

- [Upgrade Checker](https://laravelshift.com/laravel-upgrade-checker) ensures your application is fully upgraded by detecting any outdated code.
- [Laravel Fixer](https://laravelshift.com/laravel-code-fixer) automatically updates your code to the latest Laravel conventions.
- [Tests Generator](https://laravelshift.com/laravel-test-generator) intelligently generates model factories, HTTP Tests, and configuration for your application.
- [CI Generator](https://laravelshift.com/ci-generator) intelligently generates CI jobs to lint PHP, check code style, and run tests, including Dusk.

You may also use the [Shift Workbench](https://laravelshift.com/workbench) to automate common tasks for maintaining your Laravel and PHP applications.

**Comment by alexjustesen** [comment]
:x: PHP syntax errors were detected after running your Shift. Often these are simply differences between the PHP version on the Shift server (8.1) and your project. Occasionally they are misplaced lines or duplicate import statements.

You may quickly check the PHP syntax locally by running `php -l` on the following files:

- [ ] app/Jobs/DeleteResultsData.php
- [ ] app/Jobs/ExecSpeedtest.php

**Comment by masterwishx** [comment]
Dont sure if it belog to here but a little mistake of "vv" instead of 'v' in version of laravel:
Laravel vv10.9.0

image

**Comment by alexjustesen** [comment]
Noticed that too, I opened a PR with the package that handles it https://github.com/awcodes/filament-versions/pull/13

**Pull request merged**
