### PR TITLE
[Feature] Skip test when Public IP is in a list (#1714)

### LINKED ISSUE #1111: [Feature] Don't run tests when the public IP exists in a list
I have a backup internet connection that runs over a metered 4G SIM card. After 20GB is used up, the carrier starts billing me for each additional GB of usage. This can add up fairly quickly with speedtests running every 30 minutes.

It would be great if there was a field in the UI where we could put in e.g 166.141.144.0/22 and it would skip the test if the public IP falls inside that subnet.

_Originally posted by @luckman212 in https://github.com/alexjustesen/speedtest-tracker/issues/513#issuecomment-1686192485_

### PR DESCRIPTION
**Pull request by alexjustesen**
## 📃 Description

Expands on the work in #1714 that implements #1111. Massive thank you to @svenvg93 for getting this ball rolling 🤘.

closes #1111 

### ➕ Added

- `GetExternalIpAddress` action
- `Network` helper

### ✏️ Changed

- when skipping an IP address a message will be added to the result.
    - For IP match: `"127.0.0.1" was found in public IP address skip list.`
    - For IP range match: `"127.0.0.1" was found in public IP address skip list within range "127.0.0.0/24".`

### 🔧 Fixed

- use `https://icanhazip.com/` instead of `https://ifconfig.co/` to get the public IP address, it's backed by Cloudflare and less likely to be rate limited.

### CODE REVIEW

**Comment by luckman212** [comment]
Just want to clarify, to use this feature, we add the following Env var? Comma separated list of subnets/exact IPs?

Example:
```
SPEEDTEST_SKIP_IPS=25.240.0.0/16,98.76.54.32
```

**Comment by alexjustesen** [comment]
> Just want to clarify, to use this feature, we add the following Env var? Comma separated list of subnets/exact IPs?
> 
> Example:
> 
> ```
> SPEEDTEST_SKIP_IPS=25.240.0.0/16,98.76.54.32
> ```

Correct, example in the docs: https://docs.speedtest-tracker.dev/getting-started/environment-variables#speedtest

**Comment by bdleung** [comment]
Can this be used in reverse to only run tests if a public IP is on a whitelist?

**Comment by svenvg93** [comment]
> Can this be used in reverse to only run tests if a public IP is on a whitelist?

No, this can only be used to define public IPs not to run the test on.

**Pull request merged**
