### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Kristoffeh**
Add: schedule variable, as it is a feature most people are gonna want to customize

## 📃 Description

Most people are going to want to customize how often a speedtest is triggered. For several days I considered forking  this and implementing it myself, until i found out it was already possible. The primary focus of this change is to easily show newcomers that it is indeed possible.

### ✏️ Changed

- Added `SPEEDTEST_SCHEDULE` to `README.MD` (defaults to 1 hour).

### CODE REVIEW

**Comment by svenvg93** [comment]
Just my 2 cents; 
Not sure if using the hour mark as a good idea. There have been multiple issues with reports that tests on the hour mark like 9:00, 10:00 etc give less results then a few minutes later due to congestion on network or Speedtest Server.  Just to not cause more of these reports ourself ;)

**Comment by Kristoffeh** [comment]
That is a good point. I suppose it doesn't really matter what it is set to originally, personally i trigger a speedtest every 15 minutes.

**Comment by Kristoffeh** [comment]
Yeah honestly. I just wanted to have this added to the readme so that new users are aware that this is customizable. I don't know how many days/weeks i spent troubleshooting this, at some point i considered triggering the speedtest myself and just appending the data to database, but thankfully i found that environment variable hehe.

> Just my 2 cents; Not sure if using the hour mark as a good idea. There have been multiple issues with reports that tests on the hour mark like 9:00, 10:00 etc give less results then a few minutes later due to congestion on network or Speedtest Server. Just to not cause more of these reports ourself ;)

How about we can default something like `SPEEDTEST_SCHEDULE=5,15,25,35,45,55 * * * *`
While this version can be slightly harder to understand to some, this way we can avoid the full hour mark. Sure would've been nice to avoid those extra reports.

**Comment by alexjustesen** [comment]
@Kristoffeh I'm happy to add the option in but can you comment the line out so it's "disabled" by default with no schedule suggestion?

**Review by alexjustesen — APPROVED** [review]

**Pull request merged**
