### PR TITLE
Adhoc speedtest button on dashboard page

### PR DESCRIPTION
**Pull request by alexjustesen**
### Added
- adhoc "Queue Speedtest" button to the dashboard

### CODE REVIEW

**Comment by alexdelprete** [comment]
Did you see the tag semver comment for alpha.8? Don't forget the dot. WUD complains. :)

**Comment by alexjustesen** [comment]
> Did you see the tag semver comment for alpha.8? Don't forget the dot. WUD complains. :)

I did, that's why I added a milestone so pre-5am Alex with minimal coffee stops forgetting (will be fixed in the next release)

**Comment by alexdelprete** [comment]
My gosh...what time is it over there? It's noon here...12.36. :)

**Comment by alexjustesen** [comment]
> My gosh...what time is it over there? It's noon here...12.36. :)

east coast US, 6:39am

**Pull request merged**
