### PR TITLE
[Feature] Skip test when Public IP is in an list

### PR DESCRIPTION
**Pull request by svenvg93**
## 📃 Description

In some setups, backup connections may be metered, making speed tests on these connections potentially costly. To avoid running tests on these connections, users can specify an IP address or IP subnet in a Docker environment to skip the tests.

We will use the following lookup: icanhazip.com

If these values match any of the specified settings in the Docker environment, the test will be marked as skipped.

A test will be marked as skipped if:

- The current public IP is listed.
- The current public IP falls within a listed subnet.

To close https://github.com/alexjustesen/speedtest-tracker/issues/1111 

### ➕ Added

- Environment variables SPEEDTEST_SKIP_IP
    - User can set an IP, IP Subnet . For example `SPEEDTEST_SKIP_IP=192.168.1.1;10.0.0.0/24;172.16.0.0/16"`
- Add a Result status Skipped
- Add an Skip message to the results pop up
- Add the retrieved IP to the data field, so it will been shown in the results table. 

## 📷 Screenshots

Results table: 
368730074-6f376009-7963-4fab-8b07-224f395304c5

When an Single IP is Set:
Skip_IP

When an IP Subnet is set (Still called Error message, this was changed later):
Skip_IP_Subnet

### CODE REVIEW

**Comment by publi0** [comment]
Any updates on this PR? This feature would significantly streamline my workflow. I'm currently using a custom solution, but I've been eagerly awaiting this implementation for a long time! Thank you again for working on this.

**Comment by svenvg93** [comment]
It will need to be reviewed and tested. Due to the lack of time there is no ETA on this.

**Comment by publi0** [comment]
@svenvg93 I don't have any experience with PHP, but I'd be happy to try and help with the implementation if you think my Go and Java skills could be useful.  ;)

**Comment by svenvg93** [comment]
> @svenvg93 I don't have any experience with PHP, but I'd be happy to try and help with the implementation if you think my Go and Java skills could be useful. ;)

Appreciate the offer! It won't be much work to get it ready when the other PR is merged in; https://github.com/alexjustesen/speedtest-tracker/pull/1669 

As that one has a lot of changes for the graphs, I want to have those changes in here as well before making more changes  ;)

**Comment by publi0** [comment]
@alexjustesen Any news on this PR? This would help me so much 😀

**Comment by luckman212** [comment]
@publi0 Did your feature get merged? I am hoping this one makes it in too, would be so helpful!

**Review by alexjustesen — APPROVED** [review]

**Comment by luckman212** [comment]
👍

**Pull request merged**
