### PR TITLE
Add MS Teams Notifications via Webhooks

### PR DESCRIPTION
**Pull request by svenvg93**
## 📃 Description

To cross Teams of the list https://github.com/alexjustesen/speedtest-tracker/issues/40

### ➕ Added

Add Teams to the notification page
Add Teams to the settings migration
Add a placeholder for the URL

## 📷 Screenshots
Settings:
TeamsSettings

Results
TeamsResults

### CODE REVIEW

**Comment by svenvg93** [comment]
Not sure how this will work when this will happen 
https://devblogs.microsoft.com/microsoft365dev/retirement-of-office-365-connectors-within-microsoft-teams/

**Review by alexjustesen — APPROVED** [review]

**Comment by alexjustesen** [comment]
Before merging I'll need to do more research if it's worth adding MS Teams if the connector is going to start failing soon.

**Comment by alexjustesen** [comment]
@svenvg93 with MS killing off webhook support I propose we don't add MS Teams as a notification channel. If someone is using it I'm also willing to bet its a really small population.

**Comment by svenvg93** [comment]
@alexjustesen sounds like a good idea. Wouldn’t be worth it to add it now indeed.

**Comment by svenvg93** [comment]
@alexjustesen I do wanted to have a look to simplify the notifications as some are similar. And maybe optimize the page as well. Let me know what you think ☺️

**Pull request closed without merging**
