### PR TITLE
Homepage API support

### PR DESCRIPTION
**Pull request by cinderblockgames**
This is a condensed version of the code that was in the original app.  All it does is add one controller file + reference it in the api spec.  Can be used until the fully-featured API is ready.

### CODE REVIEW

**Comment by alexjustesen** [comment]
Thanks a ton for getting this going, I'm going to do some further changes to the PR. Mainly to simplify things even more...

**Comment by alexjustesen** [comment]
@cinderblockgames I pushed some code but it disappeared. Did it end up on your fork?

**Comment by cinderblockgames** [comment]
I don't see it in mine.

**Comment by cinderblockgames** [comment]
It made a branch on yours.

**Comment by alexjustesen** [comment]
> It made a branch on yours.

Opened a PR on your fork so you can checkout the change

**Comment by cinderblockgames** [comment]
@alexjustesen Works perfectly!

```
{"message":"ok","data":{"id":590,"ping":18.655,"download":201.8886,"upload":145.4566,...
```

image

**Review by alexjustesen — APPROVED** [review]

**Pull request merged**
