### PR TITLE
Filament admin panel

### PR DESCRIPTION
**Pull request by alexjustesen**
### Added
- [Filament](https://filamentphp.com/) admin panel

### Default Admin Account
- Username: `admin@example.com`
- Password: `password`

#### Authentication
image

#### Results
image
image

### CODE REVIEW

**Comment by alexdelprete** [comment]
Great news!

I just tested this, and I have a "mixed content" issue loading the admin panel. I use Traefik, with an https url, and it's pulling the site from the internal docker http url.

I already had this issue with BookStack, that is built with PHP: https://github.com/BookStackApp/BookStack/issues/1204

The guys at LinuxServer.io built the BookStack image with an APP_URL env variable to solve the issue with reverse proxies.


If I use the docker url directly it works fine.

**Comment by alexdelprete** [comment]
BTW: I noticed really low speed values, I just did a manual test with the server 4302 I configured in `config.yml`:

```shell
   Speedtest by Ookla

      Server: Vodafone IT - Milan (id: 4302)
         ISP: Tecno General S.r.l
Idle Latency:     8.64 ms   (jitter: 0.31ms, low: 8.36ms, high: 9.29ms)
    Download:   813.10 Mbps (data used: 874.1 MB)
                 42.38 ms   (jitter: 38.70ms, low: 9.66ms, high: 941.40ms)
      Upload:   261.07 Mbps (data used: 150.7 MB)
                  9.76 ms   (jitter: 0.77ms, low: 8.44ms, high: 12.24ms)
 Packet Loss:     0.0%
  Result URL: https://www.speedtest.net/result/c/158c6f1d-3278-4606-b24a-fbd142c6deec
```

Is alpha.6 still using config.yml? If that's the case, I'm worried about the performance within docker, but the old speedtest-tracker worked fine in that regard. How do I check detailed info of a single test (server used, etc.)?

**Comment by alexjustesen** [comment]
@alexdelprete do you mind opening separate issues for the two comments above? This way I don't lose them in a closed PR?

**Comment by alexdelprete** [comment]
Sorry about that, sometimes I feel like I'm in the discussions section. :)

I will open the 2 PRs.

**Pull request merged**
